language: cpp
sudo: required
dist: trusty
compiler:
- g++
os:
- windows
before_install:
- echo $LANG
- echo $LC_ALL
- git clone https://github.com/mycpptutorial/cicd.git
- chmod -R ug+xrw cicd
- if [ $TRAVIS_OS_NAME == linux ]; then ./cicd/scripts/dependencies-debian.sh; fi
- if [ $TRAVIS_OS_NAME == osx ]; then ./cicd/scripts/dependencies-osx.sh; fi
- if [ $TRAVIS_OS_NAME == windows ]; then sh ./cicd/scripts/dependencies-windows.sh; fi
script:
- sh ./cicd/scripts/build.sh .. build
after_success:
- ls -al build
- ls -al build/lib
- sh ./cicd/scripts/publish-artifact.sh
branches:
  only:
  - master
