language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- osx
- linux
before_install:
- echo $LANG
- echo $LC_ALL
- git clone https://github.com/mycpptutorial/cicd.git
- if [ $TRAVIS_OS_NAME == linux ]; then ./cicd/scripts/dependencies-debian.sh; fi
- if [ $TRAVIS_OS_NAME == osx ]; then ./cicd/scripts/dependencies-osx.sh; fi
script:
- ./cicd/scripts/build.sh .. build
after_success:
- ls -al build
- ls -al build/lib
branches:
  only:
  - master
