language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/dependencies-debian.sh; fi
- if [ $TRAVIS_OS_NAME == osx ]; then ./scripts/dependencies-osx.sh; fi
script:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/build.sh . build; fi
- if [ $TRAVIS_OS_NAME == osx ]; then ./scripts/build.sh . build; fi
branches:
  only:
  - master
