language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
ruby: 2.2.0
before_install:
- echo $LANG
- echo $LC_ALL
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/dependencies-debian.sh; fi
- if [ $TRAVIS_OS_NAME == osx ]; then ./scripts/dependencies-osx.sh; fi
script:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/build.sh; fi
- if [ $TRAVIS_OS_NAME == osx ]; then ./scripts/build.sh; fi
branches:
  only:
  - master
